services:
  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    networks:
      - app-network
    expose:
      - 9000
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio/

  minio-client:
    build: ./minio-client/.
    ports:
      - 9001:9001
    restart: always
    networks:
      - app-network
    depends_on:
      - minio

  labwebdb:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=LabWebSampleRootPasswd
      - MYSQL_DATABASE=lab_web_sample
      - MYSQL_USER=LABWEBLABWEB
      - MYSQL_PASSWORD=LabWebSampleSosd23333
    networks:
      - app-network
    expose:
      - 3306
    ports:
      - 3006:3306

  labwebredis:
    image: redis:latest
    networks:
      - app-network
    volumes:
      - redis_datadir:/data
      - redis_redis.conf:/usr/local/etc/redis/redis.conf
      - redis_logs:/logs
    expose:
      - 6379

  labwebapi:
    build: ./LabWeb.API/.
    ports:
      - 8080:8080
    restart: always
    networks:
      - app-network
    depends_on:
      - labwebdb
      - labwebredis

volumes:
  minio_data:
  minio_config:
  db_data:
  redis_datadir:
  redis_redis.conf:
  redis_logs:


networks:
  app-network:
    name: lab-web-network
    driver: bridge
